### ISSUE TITLE
Make schema injectable

### ISSUE THREAD

**Issue by danocmx** [danocmx/node-tf2-item-format#11]
Don't force tf2-static-schema and leave the choice onto the user.

**Comment by MaximilianAdF** [comment]
Hey. I've been trying for a while now to get the following to work:

const format = createFormat();
const attributes = format.parseEconItem(item, true, true)

The problem is that format is undefined, I thought it wasn't necessary to parse a schema with the function and now I'm stuck on how to get a schema. Thanks for any help, sorry if this is an obvious thing.
